language: go
sudo: false
go:
- 1.x
script:
- make
before_deploy:
- make build-all
deploy:
  provider: releases
  api_key:
    secure: U6Fsv4rfT45d3m/uno/uFZsl4TXOqNaWuIQblBrfbF8tqKCSd4hZ/SvqgbbNb4WbqDlNv9vSXHCEFmrJrBMPG8ysyCh3LtFb7ZA5R0pPIVAj8Uaq7Zyg96SiD86wdTL/IeFPfIzHWiEJPUdPVn/uERCpqWq2fvZUSm7KhGm8grf/8ORn7SYTlDVF5I4nBcQJk9bTW6rJ1PoM6RMeINcLS26g5Xrrh8xKwV5nxh3mMmq+6TeW5OEaMzBrnnuoTg8avRynRBTdvFFZI0uaamKrmzWQF2ck1qTpmDsJDDPaACNl2uIk5BDy/G2WDofH0UsTvhxHKmSZXj6zGi8Qorm9v8gwR8jd/2iq+uaCmaQBNW+C4htCSEiqkZ6ibD5tbGaAm6GDz4w6IMhZYpK/p2vsRSjVEOTdK5R2prZ68li1OhLro+7Mhk8WjRr712Uvo7cXSrWhVyi8fm4J8ZB+NVVoOBipNMCxubH68Ps/iEL4bp3sVulgyvbShuj4+3YzB0uZbZBx82inO44pHNiaEZroLjJYWNiEJoVNY+zZxgs5TZPxsQ+iPQ/BfH9gOqzStoVghFp5B0oNt5yMidRpSkBIpH+7eguQQBGWOH6SyKFspappPvtMg03vZpHwqEbQwRS+/udKvf7S9/zrLoXvBkOQwTDdoLpCQ2kAOJ4tjELmb9k=
  file: build/*
  file_glob: true
  skip_cleanup: true
  branches:
    only:
      - master
  on:
    tags: true
